id: product_manager
title: Product Manager / Product manager
job_titles:
- Product Manager
- Technical Product Manager
- Product manager
- Product manager tehnic
section_priority:
- Summary
- Technical Skills
- Professional Experience
- Projects
- Certifications
- Education
keywords:
  core:
  - Roadmapping
  - Discovery
  - Stakeholder Management
  - Prioritization
  technologies:
  - Analytics
  - A/B Testing
  - SQL
  tools:
  - Jira
  - Confluence
  - Amplitude
  - GA4
  certifications: []
  frameworks:
  - OKRs
  - RICE
  - Jobs-to-be-Done
  soft_skills: []
action_verbs:
- Implemented
- Engineered
- Automated
- Optimized
- Deployed
- Integrated
- Refactored
- Scaled
- Migrated
- Hardened
- Configured
- Monitored
- Troubleshot
- Standardized
- Documented
- Validated
- Benchmark-tested
- Instrumented
- Assessed
- Identified
- Exploited
- Triaged
- Remediated
- Investigated
- Detected
- Responded
action_verbs_ro:
- Implementat
- Proiectat
- Automatizat
- Optimizat
- Dezvoltat
- Integrat
- Refactorizat
- Scalat
- Migrat
- Intarit
- Configurat
- Monitorizat
- Depanat
- Standardizat
- Documentat
- Validat
- Instrumentat
- Containerizat
- Evaluat
- Identificat
- Exploatat
- Triat
- Remediat
- Investigat
- Detectat
- Raspuns
metrics:
- nps
- conversion
- retention
- churn
- arr
bullet_templates:
- Defined product strategy for {product}, increasing {kpi} by {percentage}% over {time}.
- Prioritized roadmap using {framework}, delivering {count} initiatives and reducing
  churn by {percentage}%.
- Partnered with engineering/design to launch {feature} impacting {users} users.
bullet_templates_ro:
- Am definit strategia pentru {product}, crescand {kpi} cu {percentage}% in {time}.
- Am prioritizat roadmap-ul folosind {framework}, livrand {count} initiative si reducand
  churn cu {percentage}%.
- Am colaborat cu echipele de engineering/design pentru {feature}, impactand {users}
  utilizatori.
template_placeholders:
- metric
- percentage
- action
- scope
- tool_or_method
- initiative
- risk_or_cost
- project
- time
- budget
- quality_or_sla
